[bumpver]
current_version = "1.3.0-alpha1"
version_pattern = "MAJOR.MINOR.PATCH[-TAGNUM]"
commit = true
tag = true
push = true

[bumpver.file_patterns]
"build.gradle" = [
    "version = '{version}'"
]
"bumpver.toml" = [
    'current_version = "{version}"',
]
